### PR TITLE
ci(terraform): Test PR comment apply trigger

### PR DESCRIPTION
**Pull request by chris3ware**
Replace draft PR approval triggering apply with adding a PR comment with the text: "terraform plan approved". Not all pull requests will relate to terraform and, because the `pull_request_review` trigger does not support the paths filter, pull request approval could trigger a terraform apply with the previous trigger.

### CODE REVIEW

**Comment by chris3ware** [comment]
terraform plan approved

**Comment by chris3ware** [comment]
terraform plan approved

**Comment by chris3ware** [comment]
terraform plan approved

**Comment by chris3ware** [comment]
> ```fish
> apply -chdir=terraform/development -lock=true tfplan
> ```
> 
> Outline of changes.
> Error: Saved plan is stale
> ###### Terraform CI by @chris3ware via [issue_comment](https://github.com/3ware/gitops-2024/actions/runs/11457561262/job/31878050369) at undefined.

Plan Parity test is working

**Review by james3ware — APPROVED** [review]

**Pull request merged**
